"""Public rail-adapter boundary for simulation engines."""

from apar.simulator.rails.a2a import (
    A2ACommand,
    A2ARailAdapter,
    AcceptA2A,
    FreezeA2AFunds,
    InitiateA2A,
    PostA2A,
    RecoverA2A,
    RejectA2A,
    ReportA2AFraud,
    ReturnA2A,
)
from apar.simulator.rails.agentic import (
    AGENTIC_TRUST_STATE_ID,
    AgenticDecision,
    AgenticPaymentCommand,
    AgenticRailAdapter,
    RiskScorer,
)
from apar.simulator.rails.base import (
    AdapterFactory,
    FrozenState,
    LedgerReader,
    LifecycleError,
    RailAdapter,
    RailContext,
    RandomCapability,
)
from apar.simulator.rails.card import (
    AuthorizeCard,
    CardCommand,
    CardRailAdapter,
    ChargebackCard,
    ClearCard,
    DeclineCardAuthorization,
    OpenCardDispute,
    RecoverCard,
    RefundCard,
    ReportCardFraud,
    ReverseCardAuthorization,
    SettleCard,
)

__all__ = [
    "AGENTIC_TRUST_STATE_ID",
    "A2ACommand",
    "A2ARailAdapter",
    "AcceptA2A",
    "AdapterFactory",
    "AgenticDecision",
    "AgenticPaymentCommand",
    "AgenticRailAdapter",
    "AuthorizeCard",
    "CardCommand",
    "CardRailAdapter",
    "ChargebackCard",
    "ClearCard",
    "DeclineCardAuthorization",
    "FreezeA2AFunds",
    "FrozenState",
    "InitiateA2A",
    "LedgerReader",
    "LifecycleError",
    "OpenCardDispute",
    "PostA2A",
    "RailAdapter",
    "RailContext",
    "RandomCapability",
    "RecoverA2A",
    "RecoverCard",
    "RefundCard",
    "RejectA2A",
    "ReportA2AFraud",
    "ReportCardFraud",
    "ReturnA2A",
    "RiskScorer",
    "ReverseCardAuthorization",
    "SettleCard",
]
